name: Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Qt 5.12.12
        uses: qmfrederik/setup-qmake@v2
        with:
          qt-version: '5.12.12'

      - name: Set up SonarQube
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          qmake
          make
