name: Sonar

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Qt 5.12.12
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev
          qmake --version

      - name: Set up SonarQube
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          entryPoint: sonar-scanner
          args: -X
          projectBaseDir: ./  # adjust this based on your project structure

      - name: Build and analyze
        run: |
          qmake
          make
